name: Publish to GH Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Default to bash
defaults:
  run:
    shell: bash
  
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps: 

    - name: Checkout
      uses: actions/checkout@v4
      if: github.ref == 'refs/heads/main'
      with:
        submodules: recursive
        fetch-depth: 0
        ref: gh-pages
        path: built-site
    - name: Setup Hugo CLI
      run: |
        curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.121.1/hugo_extended_0.121.1_linux-amd64.tar.gz'
        tar -C ${RUNNER_TEMP} -zxvf /tmp/hugo.tar.gz hugo       
    - name: Install Dart Sass
      run: sudo snap install dart-sass
    - name: Install Node.js dependencies
      run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
    - name: Build
      run: ${RUNNER_TEMP}/hugo --minify

    - name: Deploy
      if: github.ref == 'refs/heads/main'
      run: |
        cp -R public/* ${GITHUB_WORKSPACE}/built-site/
        cd ${GITHUB_WORKSPACE}/built-site
        git add .
        git config user.name 'upyesp'
        git config user.email 'upyesp@gmail.com'
        git commit -m 'Updated site'
        git push          
